### ISSUE TITLE
Git should be included in the pre-requisites

### ISSUE THREAD

**Issue by bradjohnl** [ledgerleapllc/CasperAssociationPortalBackend#23]
As cloning the repository is part of the installation instructions, "git" should be mentioned as a pre-requisite software in the readme.

**Comment by ledgerleapllc** [comment]
Commit: https://github.com/ledgerleapllc/CasperAssociationPortalBackend/commit/0705b782313d9861498d614ecfd9839be824ced3

**Comment by ledgerleapllc** [comment]
Frontend: https://github.com/ledgerleapllc/CasperAssociationPortal/commit/ffd7d0aa77c622981988eff00420669b6c02084b
